mu, std = norm.fit(entries)
print("Mean : " + str(mu) + ", " + "StDev"  + str(std) )
x_fit = np.linspace(norm.ppf(0.0001, mu, std), norm.ppf(0.9999, mu, std), 1000)
y_fit = norm.pdf(x_fit, mu, std)
fig, ax = plt.subplots(figsize=(8,8))
ax.hist(entries, bins=100, density=True, histtype='stepfilled')
ax.plot(x_fit,y_fit,c="red", linestyle="-",  linewidth=2)
ax.set_xlim(-20,20)
ax.set_ylim(0,norm.pdf(mu, mu, std)*1.3)
